# Trzeci program

*Wszystkie prezentowane tematy znajdują się na: Wykład profesora Paszyńskiego z przedmiotu Rachunek Macierzowy*
[Źródło](https://home.agh.edu.pl/~paszynsk/RM/RachunekMacierzowy3.pdf)

**Realizowane tematy:** 
Napisanie programu który dla macierzy M = macierz Tybetańska z 650 roku p.n.e. 

1. Oblicza normę macierzową ∥M∥1 (slajdy 7,10,11)

2. Oblicza współczynnik uwarunkowania macierzowy ∥M∥1  (slajd 19,20)

3. Oblicza normę macierzową ∥M∥2 (slajdy 7,15)

4. Oblicza współczynnik uwarunkowania macierzowy ∥M∥2  (slajdy 19,20,21,22,23)

5. Oblicza normę macierzową ∥M∥p (slajdy 7)

6. Oblicza współczynnik uwarunkowania macierzowy ∥M∥p (slajd 19,20)

7. Oblicza normę macierzową ∥M∥∞ (slajd 7,13)

8. Oblicza współczynnik uwarunkowania macierzowy ∥M∥∞  (slajd 19,20)

9. Oblicza SVD macierzy M (slajd 34,37, na kolejnych slajdach są obliczenia ręczne które zastępujemy zawołaniem biblioteki numerycznej)



**Przygotowali:**
- *Tomasz Bochnak*
- *Szymon Budziak*

In [1]:
import numpy as np

In [2]:
# Macierz z wykładu
M = np.array([[4, 9, 2],
              [3, 5, 7],
              [8, 1, 6]])

M

array([[4, 9, 2],
       [3, 5, 7],
       [8, 1, 6]])

## 1. Obliczenie normy macierzy M1

### Numpy norm
![image](img/norm.png)

In [3]:
m1_norm = lambda x: np.max(np.sum(x, axis=0))

print(f'Norma macierzowa M1: {m1_norm(M)}')

Norma macierzowa M1: 15


In [4]:
print(f'Norma macierzowa M1: {np.linalg.norm(M, ord=1)}')

Norma macierzowa M1: 15.0


## 2. Obliczenie współczynnika uwarunkowania macierzy M1

### Numpy cond

![image](img/cond.png)

In [5]:
cond_m1 = lambda x: np.linalg.norm(x, ord=1) * np.linalg.norm(np.linalg.inv(x), ord=1)

print(f'Współczynnik uwarunkowania macierzy M1: {cond_m1(M)}')

Współczynnik uwarunkowania macierzy M1: 5.333333333333333


In [6]:
print(f'Współczynnik uwarunkowania macierzy M1: {np.linalg.cond(M, p=1)}')

Współczynnik uwarunkowania macierzy M1: 5.333333333333333


## 3. Obliczenie normy macierzy M2

In [7]:
m2_norm = lambda x: np.linalg.svd(x, compute_uv=False)[0]

print(f'Norma macierzowa M2: {m2_norm(M)}')

Norma macierzowa M2: 15.000000000000002


In [8]:
print(f'Norma macierzowa M2: {np.linalg.norm(M, ord=2)}')

Norma macierzowa M2: 15.000000000000002


## 4. Obliczenie współczynnika uwarunkowania macierzy M2

In [9]:
def cond_m2(x: np.ndarray) -> float:
    singular_values = np.linalg.svd(x, compute_uv=False)
    return singular_values[0] / singular_values[x.shape[0] - 1]


print(f'Współczynnik uwarunkowania macierzy M2: {cond_m2(M)}')

Współczynnik uwarunkowania macierzy M2: 4.330127018922198


In [10]:
print(f'Współczynnik uwarunkowania macierzy M2: {np.linalg.cond(M, p=2)}')

Współczynnik uwarunkowania macierzy M2: 4.330127018922198


## 5. Obliczenie normy macierzowej Mp

In [11]:
p_values = [1, 2, 3]

for p in p_values:
    try:
        print(f'Norma macierzowa M{p}: {np.linalg.norm(M, ord=p)}')
    except ValueError as e:
        print(f'Norma macierzowa M{p}: {e}')

Norma macierzowa M1: 15.0
Norma macierzowa M2: 15.000000000000002
Norma macierzowa M3: Invalid norm order for matrices.


## 6. Obliczenie współczynnika uwarunkowania macierzy Mp

In [12]:
p = [1, 2, 3]

for i in p:
    try:
        print(f'Współczynnik uwarunkowania macierzy M{i}: {np.linalg.cond(M, p=i)}')
    except ValueError as e:
        print(f'Współczynnik uwarunkowania macierzy M{i}: {e}')

Współczynnik uwarunkowania macierzy M1: 5.333333333333333
Współczynnik uwarunkowania macierzy M2: 4.330127018922198
Współczynnik uwarunkowania macierzy M3: Invalid norm order for matrices.


Problemy z punktu 5 oraz 6 są jednak problemami NP-trudnymi i nie istnieje algorytm, który w czasie wielomianowym obliczyłby te wartości. Udało znaleźć się papera, który omawia ten problem:

https://arxiv.org/abs/1001.2613

## 7. Obliczenie normy macierzowej M∞

In [13]:
m_inf = lambda x: np.max(np.sum(x, axis=1))

print(f'Norma macierzowa M∞: {m_inf(M)}')

Norma macierzowa M∞: 15


In [14]:
print(f'Norma macierzowa M∞: {np.linalg.norm(M, ord=np.inf)}')

Norma macierzowa M∞: 15.0


## 8. Obliczenie współczynnika uwarunkowania macierzy M∞

In [15]:
cond_m_inf = lambda x: np.linalg.norm(x, ord=np.inf) * np.linalg.norm(np.linalg.inv(x), ord=np.inf)

print(f'Współczynnik uwarunkowania macierzy M∞: {cond_m_inf(M)}')

Współczynnik uwarunkowania macierzy M∞: 5.333333333333333


In [16]:
print(f'Współczynnik uwarunkowania macierzy M∞: {np.linalg.cond(M, p=np.inf)}')

Współczynnik uwarunkowania macierzy M∞: 5.333333333333333


## 9. Obliczenie SVD macierzy M

[SVD Wikipedia](https://en.wikipedia.org/wiki/Singular_value_decomposition)

In [17]:
def svd(matrix: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    # Step 1: Compute A * A^T
    aat = np.dot(matrix, matrix.T)

    # Step 2: Compute eigenvalues and eigenvectors of A * A^T
    eigenvalues_aat, eigenvectors_aat = np.linalg.eig(aat)

    # Sort eigenvalues and eigenvectors in descending order
    idx = eigenvalues_aat.argsort()[::-1]
    eigenvalues_aat = eigenvalues_aat[idx]
    eigenvectors_aat = eigenvectors_aat[:, idx]

    # Step 3: Compute singular values and singular vectors of the original matrix
    singular_values = np.sqrt(eigenvalues_aat)
    singular_vectors = np.dot(matrix.T, eigenvectors_aat) / singular_values

    return singular_vectors.T, singular_values, eigenvectors_aat

In [18]:
U, S, V = svd(M)

print(f'U: {U}')
print(f'S: {S}')
print(f'V: {V}')

U: [[-5.77350269e-01 -5.77350269e-01 -5.77350269e-01]
 [ 4.08248290e-01 -8.16496581e-01  4.08248290e-01]
 [ 7.07106781e-01  4.80740672e-17 -7.07106781e-01]]
S: [15.          6.92820323  3.46410162]
V: [[-5.77350269e-01 -7.07106781e-01  4.08248290e-01]
 [-5.77350269e-01  1.69222025e-16 -8.16496581e-01]
 [-5.77350269e-01  7.07106781e-01  4.08248290e-01]]


Możemy również spróbować zastosować funkcję biblioteczną z **numpy**

In [19]:
U, S, V = np.linalg.svd(M)

print(f'U: {U}')
print(f'S: {S}')
print(f'V: {V}')

U: [[-5.77350269e-01 -7.07106781e-01 -4.08248290e-01]
 [-5.77350269e-01  6.09234885e-15  8.16496581e-01]
 [-5.77350269e-01  7.07106781e-01 -4.08248290e-01]]
S: [15.          6.92820323  3.46410162]
V: [[-5.77350269e-01 -5.77350269e-01 -5.77350269e-01]
 [ 4.08248290e-01 -8.16496581e-01  4.08248290e-01]
 [-7.07106781e-01  1.16573418e-14  7.07106781e-01]]
