# Pierwszy program

**Wybrany temat:** 1

**Opis:**
Dla macierzy o rozmiarze mniejszym lub równym $2^{l}$ ×$2^{l}$ algorytm tradycyjny. Dla macierzy o rozmiarze większym od $2^{l}$ ×$2^{l}$ algorytm rekurencyjny Binéta.

**Przygotowali:**
- *Tomasz Bochnak*
- *Szymon Budziak*

## Importy

In [5]:
from time import perf_counter
import numpy as np

## Algorytm tradycyjny

In [3]:
def traditional_algorithm(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    pass

## Algorytm rekurencyjny Binéta

In [9]:
def split_matrix(M: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """
    Split a matrix into 4 sub matrices.

    Args:
        M (np.ndarray): Matrix to split

    Returns:
        tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]: Sub matrices
    """
    n = M.shape[0] // 2
    return M[:n, :n], M[:n, n:], M[n:, :n], M[n:, n:]


def binet_algorithm(A: np.ndarray, B: np.ndarray) -> tuple[np.ndarray, int]:
    """
    Binet algorithm for matrix multiplication with count of operations.

    Args:
        A (np.ndarray): First matrix to multiply
        B (np.ndarray): Second matrix to multiply

    Returns:
        tuple[np.ndarray, int]: Result of the matrix multiplication and count of all operations.
        np.ndarray: Result of the multiplication
    """
    if A.shape == (1, 1):
        return A * B, 1

    A11, A12, A21, A22 = split_matrix(A)
    B11, B12, B21, B22 = split_matrix(B)

    C11a, count1a = binet_algorithm(A11, B11)
    C11b, count1b = binet_algorithm(A12, B21)
    C12a, count2a = binet_algorithm(A11, B12)
    C12b, count2b = binet_algorithm(A12, B22)
    C21a, count3a = binet_algorithm(A21, B11)
    C21b, count3b = binet_algorithm(A22, B21)
    C22a, count4a = binet_algorithm(A21, B12)
    C22b, count4b = binet_algorithm(A22, B22)

    C1 = C11a + C11b
    C2 = C12a + C12b
    C3 = C21a + C21b
    C4 = C22a + C22b

    count = count1a + count1b + count2a + count2b + count3a + count3b + count4a + count4b + 4 * np.prod(A.shape)

    return np.vstack((np.hstack((C1, C2)), np.hstack((C3, C4)))), count

## Główna funkcja

In [12]:
def main(size: int, l: int) -> None:
    A = np.random.randint(low=0, high=10, size=(size, size))
    B = np.random.randint(low=0, high=10, size=(size, size))

    start = perf_counter()

    if size <= l:
        matrix_method = 'Traditional algorithm'
        result_matrix, total_operations = traditional_algorithm(A, B)
    else:
        matrix_method = 'Binet algorithm'
        result_matrix, total_operations = binet_algorithm(A, B)

    end = perf_counter()

    print(f'Matrix A:\n{A}\n')
    print(f'Matrix B:\n{A}\n')
    print(f'Result matrix after multiplication:\n{result_matrix}\n')
    print(f'Total execution time of {matrix_method}: {end - start:.6f} seconds')
    print(f'Total number of operations: {total_operations}')

In [13]:
size = 4
l = 3

main(size, l)

Matrix A:
[[3 9 6 1]
 [8 6 5 0]
 [1 6 7 7]
 [1 8 1 9]]

Matrix B:
[[3 9 6 1]
 [8 6 5 0]
 [1 6 7 7]
 [1 8 1 9]]

Result matrix after multiplication:
[[ 75 101  94  38]
 [100  72  83  33]
 [104  98 125  77]
 [116  80 105  91]]

Total execution time of Binet algorithm: 0.000818 seconds
Total number of operations: 256
