# Pierwszy program

**Wybrany temat:** 1

**Opis:**
Dla macierzy o rozmiarze mniejszym lub równym $2^{l}$ ×$2^{l}$ algorytm tradycyjny. Dla macierzy o rozmiarze większym od $2^{l}$ ×$2^{l}$ algorytm rekurencyjny Binéta.

**Przygotowali:**
- *Tomasz Bochnak*
- *Szymon Budziak*

## Importy

In [5]:
from time import perf_counter
import numpy as np

## Algorytm tradycyjny

In [3]:
def traditional_algorithm(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    pass

## Algorytm rekurencyjny Binéta

In [4]:
def split_matrix(M: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """
    Split a matrix into 4 sub matrices.

    Args:
        M (np.ndarray): Matrix to split

    Returns:
        tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]: Sub matrices
    """
    n = M.shape[0] // 2
    return M[:n, :n], M[:n, n:], M[n:, :n], M[n:, n:]


def binet_algorithm(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    """
    Binet algorithm for matrix multiplication.

    Args:
        A (np.ndarray): First matrix to multiply
        B (np.ndarray): Second matrix to multiply

    Returns:
        np.ndarray: Result of the multiplication
    """
    if A.shape == (1, 1):
        return A * B

    A11, A12, A21, A22 = split_matrix(A)
    B11, B12, B21, B22 = split_matrix(B)

    C1 = binet_algorithm(A11, B11) + binet_algorithm(A12, B21)
    C2 = binet_algorithm(A11, B12) + binet_algorithm(A12, B22)
    C3 = binet_algorithm(A21, B11) + binet_algorithm(A22, B21)
    C4 = binet_algorithm(A21, B12) + binet_algorithm(A22, B22)

    return np.vstack((np.hstack((C1, C2)), np.hstack((C3, C4))))

## Główna funkcja

In [7]:
def main(size: int, l: int) -> None:
    A = np.random.randint(low=0, high=10, size=(size, size))
    B = np.random.randint(low=0, high=10, size=(size, size))

    start = perf_counter()

    if size <= l:
        matrix_method = 'Traditional algorithm'
        result = traditional_algorithm(A, B)
    else:
        matrix_method = 'Binet algorithm'
        result = binet_algorithm(A, B)

    end = perf_counter()

    print(f'Matrix A:\n{A}\n')
    print(f'Matrix B:\n{A}\n')
    print(f'Result matrix after multiplication:\n{result}\n')
    print(f'Total execution time of {matrix_method}: {end - start:.6f} seconds')

In [8]:
size = 4
l = 3

main(size, l)

Matrix A:
[[7 0 2 2]
 [0 3 5 8]
 [2 7 2 0]
 [7 3 0 4]]

Matrix B:
[[7 0 2 2]
 [0 3 5 8]
 [2 7 2 0]
 [7 3 0 4]]

Result matrix after multiplication:
[[ 54  22  73  25]
 [104  64  28  37]
 [ 71  16  26  73]
 [ 73  12  67  48]]

Total execution time of Binet algorithm: 0.001784 seconds
